language: python

addons:
  firefox: "latest"

sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pip install codecov
  - npm install -g geckodriver

install: make install

script: make test-coverage functional-test

after_success: codecov
